services:
  backend1:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend1
    networks:
      app_net:
        ipv4_address: 172.31.0.2

  backend2:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend2
    networks:
      backend_net:
        ipv4_address: 172.30.0.3

  nginx:
    build: 
      context: ./app/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - backend1
      - backend2
    networks:
      app_net:
        ipv4_address: 172.31.0.4
      backend_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16